name: nice_travel
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^2.1.7
  firebase_database: ^2.0.2
  
  firebase_auth: ^0.8.0+2
  google_sign_in: ^4.0.1
  flutter_facebook_login: ^2.0.1
  
  material_design_icons_flutter: ^3.2.3595
  flutter_url_image_load_fail:
  bloc_pattern: ^2.2.0+3
  rxdart: ^0.22.0

  timeline_list: ^0.0.3
  cached_network_image:
  flutter_google_places: "0.2.3"
  autocomplete_textfield: ^1.6.7
  giffy_dialog: 1.6.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

  google_maps_flutter: "0.5.16"

  flutter_form_builder: ^3.6.1
  flutter_masked_text: ^0.8.0
  scoped_model: ^0.3.0
#  firebase_messaging: 5.1.6

dev_dependencies:
  build_runner: ^1.0.0
  json_annotation: ^2.0.0
  built_value_generator: ^6.3.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - boipeba.png
    - cityplaceholder.png
    - yes.gif
    - noo.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Regular.ttf
     - family: NiceTravelIcons
       fonts:
         - asset: fonts/icons.ttf
     - family: Literata
       fonts:
         - asset: fonts/Literata[wght].ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
